### PR TITLE
Dalight13 patch blackberrylauncher

### LINKED ISSUE #89: Adding support for BlackBerry Launcher
Is there any way I can modify LauncherHelper.java? If so how? Do I have to import library into my app or can I just add a LauncherHelper.java class into my own app?

I'm trying to add BlackBerry Launcher : https://play.google.com/store/apps/details?id=com.blackberry.blackberrylauncher

I looked into LauncherHelper.java and found out that it works perfectly with "applyManual", If I can't modify it is there any way you could add it please?

I tested my Icon Packs with the BlackBerry Launcher and they work perfectly

Thank you in advance

daLight

### PR DESCRIPTION
**Pull request by dalight13**
Adding BlackBerry Launcher!

It installs Icon Packs the same way as Evie Launcher Instrucitons.. Home Screen Long Press, Settings, Icon Packs, Apply %IconPackName%

This is to resolve #89 

This is my first ever Code Change/Pull Request, if I have done anything wrong please let me know!

### CODE REVIEW

**Comment by dalight13** [comment]
This is my first ever Code Change/Pull Request, if I have done anything wrong please let me know!

**Comment by danimahardhika** [comment]
I going to do some test first

**Comment by dalight13** [comment]
Thank you very much! Would love to help if you need me!

**Comment by danimahardhika** [comment]
This won't works

**Comment by dalight13** [comment]
Can I try one last change to it? It could also use "applyManual" instead of "applyEvie"

**Pull request closed without merging**
